using UnityEngine;
using UnityEngine.UI;

public class DebugTextDisplay : MonoBehaviour
{
    // Text is a component in Unity GameObject
    private Text _debugText;

    void Start()
    {
        // assigning Text component to the _debugText to use its properties (e.g.".text")
        _debugText = GetComponent<Text>();
    }

    private void OnEnable()
    {
        // Subscribing HandleLogMessageReceived method to Application.logMessageReceived event.
        // Application.logMessageReceived is triggered when log message is generated by Debug.Log 
        Application.logMessageReceived += HandleLogMessageReceived;
    }

    private void OnDisable()
    {
        Application.logMessageReceived -= HandleLogMessageReceived;
    }

    private void HandleLogMessageReceived(string logMessage, string stackTrace, LogType logType)
    {
        // Displaying only log messages
        if (logType == LogType.Log) 
        {
            // text property sets value to _debugText
            _debugText.text += logMessage + "\n";
        }
    }
}